apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-server
  template:
    metadata:
      labels:
        app: webhook-server
    spec:
      containers:
      - name: webhook-server
        image: coolsvap/my-webhook-server:amd64
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-server
spec:
  selector:
    app: webhook-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook-server-ingress
  annotations:
    # cert-manager.io/cluster-issuer: <<TBA>>
    nginx.ingress.kubernetes.io/rewrite-target: /webhook
spec:
  # tls:
  #   - hosts:
  #     - <<TBA>>
  #     secretName: <<TBA>>
  rules:
  - host: # Replace with your domain
    http:
      paths:
      - path: /webhook(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: webhook-server
            port:
              number: 80
